version: 2
updates:
  - directory: /
    package-ecosystem: gradle
    schedule:
      interval: weekly
    assignees:
      - MichelHartmann
      - meiXXI
  - directory: /
    package-ecosystem: github-actions
    schedule:
      interval: weekly
    assignees:
      - MichelHartmann
