name: Build

on:
  pull_request:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        java: [ 16 ]
    runs-on: ${{ matrix.os }}
    name: Java build on ${{ matrix.os }} with JDK ${{ matrix.java }}
    steps:
      - name: Setup JDK ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java }}

      - name: Check out sources...
        uses: actions/checkout@v2

      - name: Build with Gradle
        run: ./gradlew test jacocoTestReport

      - name: Submit Code coverage
        uses: codecov/codecov-action@v2
        with:
          flags: ${{ matrix.os }}, JDK ${{ matrix.java }}
          file: build/reports/jacoco/test/jacocoTestReport.xml
